Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2021-09, with the labels that each got.

#482 52 overwrite data via mqtt
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/dataprocessing.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/mqtt-to-postgresql/mqtt.go
  golang/cmd/mqtt-to-postgresql/queue.go
  golang/go.mod
  golang/go.sum
Labels: enhancement

#490 repaired merging conflict which broke uniqueProduct in mqtt-to-postgresql
  golang/cmd/mqtt-to-postgresql/database.go
Labels: bug

#431 392 update digital shadow documentation
  docs/content/en/docs/Concepts/DigitalShadow/digitalShadowConcept_image.png
  docs/content/en/docs/Concepts/DigitalShadow/index.md
  docs/content/en/docs/Concepts/DigitalShadow/timescaleDB_image.png
  docs/content/en/docs/Concepts/mqtt/index.md
Labels: documentation

#508 Update cameraconnect readme
  cameraconnect/README.md
Labels: documentation

#489 54 factoryinput
  deployment/factorycube-server/templates/factoryinput-pdb.yaml
  deployment/factorycube-server/templates/factoryinput-statefulset.yaml
  deployment/factorycube-server/templates/vernemq-configmap.yaml
  deployment/factorycube-server/values.yaml
  deployment/factoryinput/Dockerfile
  golang/cmd/factoryinput/http.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinput/mqtt.go
  golang/cmd/factoryinput/queue.go
  golang/cmd/grafana-proxy/grafana/api/user/user.go
  golang/cmd/grafana-proxy/http.go
  golang/cmd/grafana-proxy/main.go
Labels: enhancement

#510 feat: Added maintenanceactivities table
  deployment/factorycube-server/templates/timescale-configmap.yaml
Labels: bug

#526 feat: Updated documentation for factoryinput, grafana-proxy and umh-panel
  docs/content/en/docs/Developers/factorycube-server/factoryinput/index.md
  docs/content/en/docs/Developers/factorycube-server/grafana-plugins/umh-factoryinput-panel/grafana_panel.png
  docs/content/en/docs/Developers/factorycube-server/grafana-plugins/umh-factoryinput-panel/grafana_to_mqtt_stack.svg
  docs/content/en/docs/Developers/factorycube-server/grafana-plugins/umh-factoryinput-panel/index.md
  docs/content/en/docs/Developers/factorycube-server/grafana-proxy/index.md
Labels: documentation

#506 500 problem with queue locking
  deployment/factorycube-server/templates/mqtttopostgresql-statefulset.yaml
  deployment/factorycube-server/templates/timescale-configmap.yaml
  golang/cmd/factoryinsight/database.go
  golang/cmd/factoryinsight/dataprocessing.go
  golang/cmd/factoryinsight/dataprocessing_test.go
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/dataprocessing.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/mqtt-to-postgresql/mqtt.go
  golang/cmd/mqtt-to-postgresql/prefix.go
  golang/cmd/mqtt-to-postgresql/processAddOrder.go
  golang/cmd/mqtt-to-postgresql/processAddParentToChild.go
  golang/cmd/mqtt-to-postgresql/processAddProduct.go
  golang/cmd/mqtt-to-postgresql/processAddShift.go
  golang/cmd/mqtt-to-postgresql/processCountData.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftByAssetIdAndBeginTime.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftById.go
  golang/cmd/mqtt-to-postgresql/processEndOrder.go
  golang/cmd/mqtt-to-postgresql/processMaintenanceActivity.go
  golang/cmd/mqtt-to-postgresql/processModifyProducedPiece.go
  golang/cmd/mqtt-to-postgresql/processModifyState.go
  golang/cmd/mqtt-to-postgresql/processProductTag.go
  golang/cmd/mqtt-to-postgresql/processProductTagString.go
  golang/cmd/mqtt-to-postgresql/processRecommendationData.go
  golang/cmd/mqtt-to-postgresql/processScrapCount.go
  golang/cmd/mqtt-to-postgresql/processScrapUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processStartOrder.go
  golang/cmd/mqtt-to-postgresql/processState.go
  golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go
  golang/cmd/mqtt-to-postgresql/processUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processValueData.go
  golang/cmd/mqtt-to-postgresql/processValueString.go
  golang/cmd/mqtt-to-postgresql/process_.go
  golang/cmd/mqtt-to-postgresql/queue.go
  golang/cmd/mqtt-to-postgresql/queueHandler.go
  golang/cmd/mqtt-to-postgresql/statements.go
  golang/go.mod
  golang/go.sum
  golang/internal/cache.go
Labels: bug, enhancement, go

#537 Fixes MQTT-to-postgres queue locking, if product doesn't exits
  deployment/factorycube-server/templates/mqtttopostgresql-statefulset.yaml
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/mqtt.go
  golang/cmd/mqtt-to-postgresql/processAddOrder.go
  golang/cmd/mqtt-to-postgresql/processAddParentToChild.go
  golang/cmd/mqtt-to-postgresql/processAddProduct.go
  golang/cmd/mqtt-to-postgresql/processAddShift.go
  golang/cmd/mqtt-to-postgresql/processCountData.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftByAssetIdAndBeginTime.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftById.go
  golang/cmd/mqtt-to-postgresql/processEndOrder.go
  golang/cmd/mqtt-to-postgresql/processMaintenanceActivity.go
  golang/cmd/mqtt-to-postgresql/processModifyProducedPiece.go
  golang/cmd/mqtt-to-postgresql/processModifyState.go
  golang/cmd/mqtt-to-postgresql/processProductTag.go
  golang/cmd/mqtt-to-postgresql/processProductTagString.go
  golang/cmd/mqtt-to-postgresql/processRecommendationData.go
  golang/cmd/mqtt-to-postgresql/processScrapCount.go
  golang/cmd/mqtt-to-postgresql/processScrapUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processStartOrder.go
  golang/cmd/mqtt-to-postgresql/processState.go
  golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go
  golang/cmd/mqtt-to-postgresql/processUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processValueData.go
  golang/cmd/mqtt-to-postgresql/processValueString.go
  golang/cmd/mqtt-to-postgresql/process_.go
  golang/cmd/mqtt-to-postgresql/statements.go
  golang/internal/cache.go
Labels: bug, go
