Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2021-11, with the labels that each got.

#620 471 grafana-will-not-start-after-reboot-without-internet-connection
  deployment/factorycube-server/values.yaml
Labels: type: bug, lang: k8s

#621 604 Install script should not continue if encountering an error
  docs/static/examples/development.yaml
Labels: type: enhancement

#619 576 current migrations not according to specs
  deployment/factorycube-server/templates/timescale-configmap.yaml
Labels: type: bug

#606 560 default flow in node red causing crash of mqtt to postgresql
  deployment/mqtt-to-postgresql/Dockerfile
  docs/content/en/docs/Developers/factorycube-server/mqtt-to-postgresql/MQTT-Flow.drawio
  docs/content/en/docs/Developers/factorycube-server/mqtt-to-postgresql/MQTT-Flow.svg
  docs/content/en/docs/Developers/factorycube-server/mqtt-to-postgresql/index.md
  golang/cmd/grafana-proxy/main.go
  golang/cmd/mqtt-bridge/queue.go
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/mqtt-to-postgresql/mqtt.go
  golang/cmd/mqtt-to-postgresql/processAddOrder.go
  golang/cmd/mqtt-to-postgresql/processAddParentToChild.go
  golang/cmd/mqtt-to-postgresql/processAddProduct.go
  golang/cmd/mqtt-to-postgresql/processAddShift.go
  golang/cmd/mqtt-to-postgresql/processCountData.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftByAssetIdAndBeginTime.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftById.go
  golang/cmd/mqtt-to-postgresql/processEndOrder.go
  golang/cmd/mqtt-to-postgresql/processMaintenanceActivity.go
  golang/cmd/mqtt-to-postgresql/processModifyProducedPiece.go
  golang/cmd/mqtt-to-postgresql/processModifyState.go
  golang/cmd/mqtt-to-postgresql/processProductTag.go
  golang/cmd/mqtt-to-postgresql/processProductTagString.go
  golang/cmd/mqtt-to-postgresql/processRecommendationData.go
  golang/cmd/mqtt-to-postgresql/processScrapCount.go
  golang/cmd/mqtt-to-postgresql/processScrapUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processStartOrder.go
  golang/cmd/mqtt-to-postgresql/processState.go
  golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go
  golang/cmd/mqtt-to-postgresql/processUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processValueData.go
  golang/cmd/mqtt-to-postgresql/processValueString.go
  golang/cmd/mqtt-to-postgresql/process_.go
  golang/cmd/mqtt-to-postgresql/queue.go
  golang/cmd/mqtt-to-postgresql/statements.go
  golang/internal/cache.go
Labels: type: bug, lang: go

#667 fix: This aims to fix the long wait time observed in #660 by reducing the queue timeout on error.
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go
  golang/cmd/mqtt-to-postgresql/statements.go
Labels: type: bug, lang: go

#691 feat: add favicon to documentation
  docs/config.toml
  docs/layouts/partials/head.html
  docs/static/favicon.png
Labels: type: documentation, type: enhancement

#679 feat: Add Kafka to Kubernetes
  deployment/factorycube-server/Chart.yaml
  deployment/factorycube-server/templates/_helpers.tpl
  deployment/factorycube-server/templates/kafka-statefulset.yaml
  deployment/factorycube-server/values.yaml
Labels: lang: k8s

#690 feat: fix long time between mqtt message and readable message in dashboard
  golang/cmd/mqtt-to-postgresql/database.go
  golang/cmd/mqtt-to-postgresql/mqtt.go
  golang/cmd/mqtt-to-postgresql/processAddOrder.go
  golang/cmd/mqtt-to-postgresql/processAddParentToChild.go
  golang/cmd/mqtt-to-postgresql/processAddProduct.go
  golang/cmd/mqtt-to-postgresql/processAddShift.go
  golang/cmd/mqtt-to-postgresql/processCountData.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftByAssetIdAndBeginTime.go
  golang/cmd/mqtt-to-postgresql/processDeleteShiftById.go
  golang/cmd/mqtt-to-postgresql/processEndOrder.go
  golang/cmd/mqtt-to-postgresql/processMaintenanceActivity.go
  golang/cmd/mqtt-to-postgresql/processModifyProducedPiece.go
  golang/cmd/mqtt-to-postgresql/processModifyState.go
  golang/cmd/mqtt-to-postgresql/processProductTag.go
  golang/cmd/mqtt-to-postgresql/processProductTagString.go
  golang/cmd/mqtt-to-postgresql/processRecommendationData.go
  golang/cmd/mqtt-to-postgresql/processScrapCount.go
  golang/cmd/mqtt-to-postgresql/processScrapUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processStartOrder.go
  golang/cmd/mqtt-to-postgresql/processState.go
  golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go
  golang/cmd/mqtt-to-postgresql/processUniqueProduct.go
  golang/cmd/mqtt-to-postgresql/processValueData.go
  golang/cmd/mqtt-to-postgresql/processValueString.go
  golang/cmd/mqtt-to-postgresql/process_.go
  golang/internal/exponential_backoff.go
Labels: type: enhancement, lang: go

#687 feat: change mqtt to blob to use kafka instead of mqtt
  deployment/factorycube-server/templates/kafkatoblob-deployment.yaml
  deployment/factorycube-server/templates/kafkatoblob-pdb.yaml
  deployment/factorycube-server/values.yaml
  deployment/kafka-to-blob/Dockerfile
  golang/cmd/kafka-to-blob/kafka.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-blob/minio.go
  golang/cmd/kafka-to-blob/rawImage.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement, lang: go

#688 archive: python sdk
  docs/content/en/docs/Developers/_index.md
  python-sdk/.gitignore
  python-sdk/PROJECT_DEPRECATED
  python-sdk/README.md
  python-sdk/azure-pipelines.yml
  python-sdk/example/ia-dpl-counter/Dockerfile
  python-sdk/example/ia-dpl-counter/default.env
  python-sdk/example/ia-dpl-counter/docker-compose.yml
  python-sdk/example/ia-dpl-counter/src/DiscreteCounter/DiscreteCounter.py
  python-sdk/example/ia-dpl-counter/src/DiscreteCounter/__init__.py
  python-sdk/example/ia-dpl-counter/src/__init__.py
  python-sdk/example/ia-dpl-counter/src/main.py
  python-sdk/example/ia-dpl-counter/src/tests/__init__.py
  python-sdk/example/ia-dpl-counter/src/tests/test_counter.py
  python-sdk/requirements.txt
  python-sdk/src/dpl/__init__.py
  python-sdk/src/dpl/buffer.py
  python-sdk/src/setup.py
  python-sdk/src/tests/__init__.py
  python-sdk/src/tests/dummy_test_classes.py
  python-sdk/src/tests/test_point_buffer.py
  python-sdk/src/tests/test_timeseries.py
Labels: flag: archive

#676 feat: Add mqtt kafka bridge
  deployment/factorycube-server/templates/mqtt-kafka-bridge-deployment.yaml
  deployment/factorycube-server/templates/mqtt-kafka-bridge-pdb.yaml
  deployment/factorycube-server/values.yaml
  deployment/kafka-debug/Dockerfile
  deployment/mqtt-kafka-bridge/Dockerfile
  golang/cmd/kafka-debug/kafka.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/mqtt-kafka-bridge/hash.go
  golang/cmd/mqtt-kafka-bridge/kafka.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/mqtt.go
  golang/cmd/mqtt-kafka-bridge/queue.go
  golang/go.mod
  golang/go.sum
  golang/internal/cache.go
Labels: type: enhancement, lang: go

#700 fix: kafka statefulset not starting
  deployment/factorycube-server/values.yaml
Labels: type: bug

#711 feat: Added pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: type: enhancement

#713 feat: add git hooks
  .githooks/config.json
  .githooks/functions/git.py
  .githooks/functions/helper.py
  .githooks/functions/ilib.py
  .githooks/functions/libhelmlint.py
  .githooks/functions/libyamllint.py
  .githooks/functions/log.py
  .githooks/pre-push
  CONTRIBUTING.md
Labels: type: enhancement, lang: python

#714 docs: update digital shadow documentation
  docs/content/en/docs/Concepts/DigitalShadow/index.md
  docs/content/en/docs/Concepts/mqtt/index.md
Labels: type: documentation

#720 fix: lint when no upstream is present
  .githooks/functions/libhelmlint.py
  .githooks/functions/libyamllint.py
Labels: lang: python

#729 Various Kafka fixes created on v0.9.0 branch
  deployment/factorycube-server/Chart.lock
  deployment/factorycube-server/charts/kafka-14.4.1.tgz
  deployment/factorycube-server/templates/_helpers.tpl
  deployment/factorycube-server/templates/kafka-statefulset.yaml
  deployment/factorycube-server/templates/kafkatoblob-deployment.yaml
  deployment/factorycube-server/templates/mqtt-kafka-bridge-deployment.yaml
  deployment/factorycube-server/values.yaml
Labels: lang: k8s

#693 docs: new project description
  README.md
Labels: type: documentation
