Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-09, with the labels that each got.

#1246 refactor: unify logging handling using umh-utils library
  golang/cmd/barcodereader/main.go
  golang/cmd/custom-microservice-tester/main.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/sensorconnect/main.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement, lang: go

#1268 fix: added PVS to mqtt->kafka regex
  golang/internal/kafkaTopics.go
Labels: type: bug

#1274 feat: hint for login screen
  docs/static/examples/development.yaml
Labels: type: enhancement, lang: go

#1273 ci: added auto update
  .github/workflows/autoupdate.yaml
Labels: type: enhancement

#1276 feat: remove remaining mqtt-to-postgres code artifacts
  .github/workflows/docker-image-mqtt-to-postgresql.yml
  deployment/barcodereader/testdata/values-minimal.yaml
  deployment/united-manufacturing-hub/values.yaml
Labels: type: bug

#1279 Fix test issues from merges during pr being open
  golang/cmd/barcodereader/main.go
  golang/cmd/custom-microservice-tester/main.go
  golang/cmd/factoryinput/http.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinput/mqtt.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/grafana/api/user/orgs.go
  golang/cmd/grafana-proxy/grafana/api/user/user.go
  golang/cmd/grafana-proxy/http.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-bridge/mqtt.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/mqtt.go
  golang/cmd/sensorconnect/downloadPortModeData.go
  golang/cmd/sensorconnect/downloadSensorData.go
  golang/cmd/sensorconnect/iolinkDeviceFinder.go
  golang/cmd/sensorconnect/main.go
  golang/cmd/sensorconnect/mqtt.go
  golang/cmd/sensorconnect/processIoddFiles.go
  golang/cmd/sensorconnect/processIoddFiles_test.go
  golang/cmd/sensorconnect/processSensorData_test.go
  golang/internal/ioddfinder.go
Labels: type: enhancement, type: ci

#1277 Adds scheduler for pull_request against main and also runs every hour
  .github/workflows/autoupdate.yaml
Labels: type: ci
