Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-03, with the labels that each got.

#894 fix: 892
  deployment/united-manufacturing-hub/templates/barcodereader-Deployment.yaml
  deployment/united-manufacturing-hub/templates/cameraconnect-Deployment.yaml
  deployment/united-manufacturing-hub/templates/mqttbridge-Deployment.yaml
  deployment/united-manufacturing-hub/templates/nodered-flows-ConfigMap.yaml
  deployment/united-manufacturing-hub/values.yaml
Labels: type: bug

#898 897 update docs
  docs/content/en/docs/Developers/united-manufacturing-hub/environment-variables/index.md
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/index.md
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/sensorconnectOverviewImage.png
Labels: type: documentation

#902 Builds and pushes docker container based on branch name.
  .github/workflows/docker-image-barcodereader.yml
  .github/workflows/docker-image-cameraconnect.yml
  .github/workflows/docker-image-factoryinput.yml
  .github/workflows/docker-image-factoryinsight.yml
  .github/workflows/docker-image-grafana-proxy.yml
  .github/workflows/docker-image-kafka-debug.yml
  .github/workflows/docker-image-kafka-init.yml
  .github/workflows/docker-image-kafka-to-blob.yml
  .github/workflows/docker-image-mqtt-bridge.yml
  .github/workflows/docker-image-mqtt-kafka-bridge.yml
Labels: type: ci

#913 Added missing documentation step when using lens
  docs/content/en/docs/Tutorials/united-manufacturing-hub/working-with-helm-and-lens/index.md
Labels: type: documentation

#916 Merged duplicate kafka code
  deployment/kafka-debug/Dockerfile
  deployment/kafka-init/Dockerfile
  deployment/kafka-to-blob/Dockerfile
  deployment/mqtt-kafka-bridge/Dockerfile
  deployment/united-manufacturing-hub/values.yaml
  golang/cmd/kafka-debug/kafka.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/kafka.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-to-blob/kafka.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/mqtt-kafka-bridge/kafka.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/internal/kafka.go
Labels: type: enhancement

#907 fix: Changed liveness probe for kafka to 180 sec from 10
  deployment/united-manufacturing-hub/values.yaml
Labels: type: bug

#908 docs: Added documentation for generating certificates for ip adresses
  docs/content/en/docs/Tutorials/general/pki/index.md
Labels: type: documentation
