Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-10, with the labels that each got.

#1261 Added index for faster GF queries
  .golangci.yaml
  deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
  golang/cmd/factoryinsight/database.go
  golang/cmd/factoryinsight/http.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement, lang: go

#1291 Feat/1289/update helm values
  deployment/helm-repo/cloud-init/development.yaml
  deployment/united-manufacturing-hub/values.yaml
  docs/static/examples/development.yaml
Labels: type: enhancement, lang: k8s

#1297 Microservice for applying migrations automatically
  .golangci.yaml
  deployment/united-manufacturing-hub/templates/_helpers.tpl
  deployment/united-manufacturing-hub/templates/automigrate/deployment.yaml
  deployment/united-manufacturing-hub/templates/automigrate/priorityClass.yaml
  deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
  deployment/united-manufacturing-hub/values.yaml
  golang/cmd/automigrate/database.go
  golang/cmd/automigrate/main.go
  golang/cmd/automigrate/migrations/0/10/0.go
  golang/cmd/automigrate/migrations/migration.go
  golang/cmd/automigrate/migrations/migration_test.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement

#1294 Timescale changes for new datamodel
  .githooks/pre-push
  .golangci.yaml
  deployment/automigrate/Dockerfile
  deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
  golang/cmd/automigrate/database.go
  golang/cmd/automigrate/database/database.go
  golang/cmd/automigrate/main.go
  golang/cmd/automigrate/migrations/0/10/0.go
  golang/cmd/automigrate/migrations/migration.go
  golang/cmd/automigrate/migrations/migration_test.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement

#1312 fix: updated values for new datamodel
  deployment/united-manufacturing-hub/values.yaml
Labels: type: bug
