Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-02, with the labels that each got.

#834 feat: Added docs for mqtt-kafka-bridge
  docs/content/en/docs/Developers/factorycube-server/mqtt-kafka-bridge/index.md
Labels: type: documentation

#824 Fix/823/githook not working
  .githooks/functions/helper.py
  CONTRIBUTING.md
Labels: type: bug

#805 feat: rewritten sensorconnect
  .gitignore
  deployment/sensorconnect/Dockerfile
  deployment/sensorconnect/config.yaml
  deployment/sensorconnect/docker-compose.yml
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/templates/nodered-flows-ConfigMap.yaml
  deployment/united-manufacturing-hub/templates/nodered-statefulset.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect-PersistentVolumeClaim.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect-deployment.yaml
  deployment/united-manufacturing-hub/values.yaml
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/index.md
  golang/cmd/sensorconnect/downloadPortModeData.go
  golang/cmd/sensorconnect/downloadPortModeData_test.go
  golang/cmd/sensorconnect/downloadSensorData.go
  golang/cmd/sensorconnect/downloadSensorData_test.go
  golang/cmd/sensorconnect/iolinkDeviceFinder.go
  golang/cmd/sensorconnect/iolinkDeviceFinder_test.go
  golang/cmd/sensorconnect/kafka.go
  golang/cmd/sensorconnect/main.go
  golang/cmd/sensorconnect/mqtt.go
  golang/cmd/sensorconnect/processIoddFiles.go
  golang/cmd/sensorconnect/processIoddFiles_test.go
  golang/cmd/sensorconnect/processSensorData.go
  golang/cmd/sensorconnect/processSensorData_test.go
  golang/internal/cache.go
  golang/internal/ioddfinder.go
  golang/internal/ioddfinder_test.go
Labels: type: enhancement, lang: go

#847 chore: Updated grafana chart to version 6.21.1
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/grafana-6.13.5.tgz
Labels: lang: k8s

#845 chore: Updated redis chart to version 16.2.0
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/redis-12.7.3.tgz
  deployment/united-manufacturing-hub/values.yaml
Labels: lang: k8s

#846 chore: Updated vernemq chart to version 1.6.12-1
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/vernemq-1.6.7.tgz
Labels: lang: k8s

#848 chore: Updated timescaledb-single to version 0.10.0
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/timescaledb-single-0.9.0.tgz
  deployment/united-manufacturing-hub/values.yaml
Labels: lang: k8s

#844 chore: Updated kafka chart to version 15.0.0
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/kafka-14.4.1.tgz
  deployment/united-manufacturing-hub/values.yaml
Labels: lang: k8s

#849 chore: Updated minio-operator to version 4.3.7
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/minio-operator-4.1.7.tgz
Labels: lang: k8s

#850 docs: Added stale docs from pr #705.
  docs/content/en/docs/Concepts/mqtt/index.md
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/index.md
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/sensorconnectOverview.drawio
  docs/content/en/docs/Developers/united-manufacturing-hub/sensorconnect/sensorconnectOverviewImage.png
Labels: type: documentation

#870 fix: fixed incorrect mount path in sensorconnect.
  deployment/united-manufacturing-hub/templates/sensorconnect-deployment.yaml
Labels: type: bug

#884 Fixes barcodereader not starting
  barcodereader/src/main.py
  deployment/united-manufacturing-hub/templates/barcodereader-Deployment.yaml
Labels: type: bug
