Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-01, with the labels that each got.

#789 feat: Improve code quality checking lints
  .githooks/functions/helper.py
  .githooks/functions/libdockerlint.py
  .githooks/functions/libgovet.py
  .githooks/functions/libstaticcheck.py
  .githooks/pre-push
Labels: type: enhancement

#787 fix: setting user to jeremy bypasses user authentication in factoryinsight
  golang/cmd/factoryinput/http.go
  golang/cmd/factoryinsight/http.go
Labels: type: bug, lang: go, type: security

#786 feat: replace jaeger client go with open telemetry
  golang/cmd/factoryinput/http.go
  golang/cmd/factoryinsight/database.go
  golang/cmd/factoryinsight/dataprocessing.go
  golang/cmd/factoryinsight/dataprocessing_shifts.go
  golang/cmd/factoryinsight/dataprocessing_test.go
  golang/cmd/factoryinsight/http.go
  golang/cmd/grafana-proxy/http.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement, type: dependencies, lang: go

#791 fix: CWE 117
  golang/cmd/factoryinput/http.go
  golang/cmd/factoryinsight/http.go
  golang/cmd/grafana-proxy/http.go
  golang/internal/sanitized_logger.go
Labels: type: enhancement, lang: go, type: security

#678 feat: Improve guide connecting machines and creating dashboards
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/complete nodered flow.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/filter.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/function.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/function_button_bar.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/function_inductive_sensor.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/function_light_barrier.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_1.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_2.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_3.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_button_bar_1.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_capacitive_sensor_1.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_light_barrier_1.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/grafana_light_barrier_2.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/ip_range_lens_1.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/ip_range_lens_2.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/json.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/logos.drawio
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/logos_doc.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/mqtt_in.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/mqtt_out.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/node_red_flow_final.json
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_flow_addshift.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_flow_button_bar.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_flow_inductive_sensor.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_flow_light_barrier.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_general.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_inputs.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_outputs.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/nodered_testing.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/switch.png
  docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/trigger.png
  docs/static/examples/node_red_flow_final.json
Labels: type: documentation

#801 fix: default values for productTable are inserted incorrectly
  deployment/factorycube-server/templates/timescale-configmap.yaml
Labels: type: bug

#806 feat: Added kowl
  deployment/factorycube-server/Chart.lock
  deployment/factorycube-server/Chart.yaml
  deployment/factorycube-server/charts/kowl-2.3.0.tgz
  deployment/factorycube-server/values.yaml
Labels: type: enhancement

#808 fix: fixed deprecation warnings
  deployment/factorycube-server/templates/factoryinput-pdb.yaml
  deployment/factorycube-server/templates/factoryinsight-hpa.yaml
  deployment/factorycube-server/templates/factoryinsight-pdb.yaml
  deployment/factorycube-server/templates/kafkatoblob-pdb.yaml
  deployment/factorycube-server/templates/mqtt-kafka-bridge-pdb.yaml
  deployment/factorycube-server/templates/mqtttoblob-pdb.yaml
  deployment/factorycube-server/templates/mqtttopostgresql-pdb.yaml
Labels: type: enhancement, lang: k8s

#821 feat: Added bashfile to compile all containers.
  deployment/python-sdk/Dockerfile
  deployment/python-sdk/dpl-arm.dockerfile
  golang/cmd/factoryinput/http.go
  golang/cmd/grafana-proxy/http.go
  tools/compile_all_containers.sh
Labels: type: enhancement, lang: docker
