Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2022-05, with the labels that each got.

#1060 Fixed crash in pxAddOrder
  golang/cmd/kafka-to-postgresql/pxAddProduct.go
Labels: type: bug, flag: high priority

#1058 Changed logging to ecs
  deployment/united-manufacturing-hub/templates/factoryinsight-deployment.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect-deployment.yaml
  deployment/united-manufacturing-hub/values.yaml
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/sensorconnect/main.go
  golang/go.mod
  golang/go.sum
Labels: type: enhancement

#1061 Added index for processValueTable & processValueStringTable on valuename to massively increase speed
  deployment/united-manufacturing-hub/templates/timescale-configmap.yaml
Labels: type: enhancement

#1042 fix: fixed sensorconnect null pointer
  golang/cmd/sensorconnect/kafka.go
Labels: type: bug

#1069 Better error logging for putback messages
  golang/cmd/kafka-to-postgresql/_pxTemplate.go
  golang/cmd/kafka-to-postgresql/highIntegrityProcessor.go
  golang/cmd/kafka-to-postgresql/pxAddOrder.go
  golang/cmd/kafka-to-postgresql/pxAddParentToChild.go
  golang/cmd/kafka-to-postgresql/pxAddProduct.go
  golang/cmd/kafka-to-postgresql/pxAddShift.go
  golang/cmd/kafka-to-postgresql/pxCount.go
  golang/cmd/kafka-to-postgresql/pxEndOrder.go
  golang/cmd/kafka-to-postgresql/pxProductTag.go
  golang/cmd/kafka-to-postgresql/pxProductTagString.go
  golang/cmd/kafka-to-postgresql/pxScrapCount.go
  golang/cmd/kafka-to-postgresql/pxScrapUniqueProduct.go
  golang/cmd/kafka-to-postgresql/pxStartOrder.go
  golang/cmd/kafka-to-postgresql/pxState.go
  golang/cmd/kafka-to-postgresql/pxUniqueProduct.go
Labels: type: enhancement

#1071 Fixed barcodereader null pointer
  golang/cmd/barcodereader/main.go
Labels: type: bug

#1073 Better error handling for create topic timeout
  golang/cmd/sensorconnect/iolinkDeviceFinder.go
Labels: type: enhancement

#1074 Removed default node-red plugin installer
  deployment/united-manufacturing-hub/templates/nodered-statefulset.yaml
  deployment/united-manufacturing-hub/values.yaml
Labels: type: enhancement

#1077 Grafana install error
  deployment/united-manufacturing-hub/values.yaml
Labels: type: bug

#1079 hide internal values and development yaml files
  .gitignore
Labels: type: enhancement

#1078 feat: Init container for kafkatopostgresql
  deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
  deployment/united-manufacturing-hub/values.yaml
Labels: type: enhancement

#1088 fix: doc build 2
  docs/content/en/docs/Tutorials/united-manufacturing-hub/certified-devices/machineconnect/index.md
Labels: type: bug, type: documentation

#1085 fix: fixed barcodereader template tried to pull map instead of string
  deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
Labels: type: bug

#1090 fix: kafka-to-postgres to able to add shifts
  golang/cmd/kafka-to-postgresql/pxAddShift.go
Labels: type: bug

#1086 fix: mqtt-kafka-bridge not starting with kafka mtls
  deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml
Labels: type: bug

#1105 Replaced all kafka topic parsing regex with a single implementation
  docs/content/en/docs/Concepts/mqtt/index.md
  golang/go.mod
  golang/go.sum
  golang/internal/ioddfinder_test.go
  golang/internal/kafka.go
  golang/internal/kafkaMessageProcessing.go
  golang/internal/kafkaTopics.go
  golang/internal/kafkaTopics_test.go
  golang/internal/topicValidator.go
Labels: type: documentation, type: enhancement, lang: go

#1109 Fixed count optional scrap field and activated pprof memory tracing
  golang/cmd/barcodereader/main.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/kafka-to-postgresql/pxAddOrder.go
  golang/cmd/kafka-to-postgresql/pxAddParentToChild.go
  golang/cmd/kafka-to-postgresql/pxAddProduct.go
  golang/cmd/kafka-to-postgresql/pxAddShift.go
  golang/cmd/kafka-to-postgresql/pxCount.go
  golang/cmd/kafka-to-postgresql/pxEndOrder.go
  golang/cmd/kafka-to-postgresql/pxProductTag.go
  golang/cmd/kafka-to-postgresql/pxProductTagString.go
  golang/cmd/kafka-to-postgresql/pxScrapCount.go
  golang/cmd/kafka-to-postgresql/pxScrapUniqueProduct.go
  golang/cmd/kafka-to-postgresql/pxStartOrder.go
  golang/cmd/kafka-to-postgresql/pxState.go
  golang/cmd/kafka-to-postgresql/pxUniqueProduct.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-to-postgresql/main.go
  golang/cmd/sensorconnect/main.go
  golang/internal/helper.go
Labels: type: bug

#1115 Fixes incorrect url in install script and duplicate volumes definition for kafkabridge
  deployment/united-manufacturing-hub/templates/kafkabridge/deployment.yaml
  docs/static/examples/development.yaml
Labels: type: bug

#1116 release: 0.9.4-prerelease5
  deployment/helm-repo/index.yaml
  deployment/helm-repo/united-manufacturing-hub-0.9.4-prerelease5.tgz
  deployment/united-manufacturing-hub/Chart.yaml
Labels: type: bug

#1118 Incorrect cast from nullptr to float64
  golang/cmd/factoryinsight/database.go
  golang/cmd/kafka-init/kafka.go
  golang/cmd/kafka-init/main.go
  golang/internal/kafka.go
Labels: type: bug
