Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2023-04, with the labels that each got.

#1532 fix: changed links from docker to GHCR
  deployment/united-manufacturing-hub/values.yaml
Labels: lang: k8s

#1547 Replace kafka with redpanda
  .github/workflows/test-umh-full-deployment.yml
  .github/workflows/test-umh-tiny-deployment.yml
  deployment/united-manufacturing-hub/templates/barcodereader/secret.yaml
  deployment/united-manufacturing-hub/templates/event-broker/service.yaml
  deployment/united-manufacturing-hub/templates/kafka-state-detector/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafka-state-detector/secret.yaml
  deployment/united-manufacturing-hub/templates/kafka/secret.yaml
  deployment/united-manufacturing-hub/templates/kafkabridge/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafkabridge/local-secret.yaml
  deployment/united-manufacturing-hub/templates/kafkabridge/remote-secret.yaml
  deployment/united-manufacturing-hub/templates/kafkadebug/secret.yaml
  deployment/united-manufacturing-hub/templates/kafkainit/secret.yaml
  deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafkatopostgresql/secret.yaml
  deployment/united-manufacturing-hub/templates/kowl/secret.yaml
  deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml
  deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/secret-kafka.yaml
  deployment/united-manufacturing-hub/templates/nodered/secret.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect/deployment.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect/secret-kafka.yaml
  deployment/united-manufacturing-hub/values.yaml
  test/test-values-full.yaml
  test/test-values-tiny.yaml
Labels: status: ready for review

#1548 Add Makefile
  Makefile
  README.md
Labels: status: in progress

#1562 Overhaul Makefile
  Makefile
Labels: status: ready for review

#1556 Add unit tests for factoryinsight v2 service-tag
  golang/cmd/factoryinsight/v2/services/service-tags_test.go
Labels: status: ready for review

#1560 Fix: getProductionspeed
  golang/cmd/factoryinsight/v1/database.go
Labels: status: ready for review

#1572 Remove conflicting flags from `go build` command
  deployment/barcodereader/Dockerfile
  deployment/custom-microservice-tester/Dockerfile
  deployment/factoryinput/Dockerfile
  deployment/factoryinsight/Dockerfile
  deployment/grafana-proxy/Dockerfile
  deployment/kafka-bridge/Dockerfile
  deployment/kafka-debug/Dockerfile
  deployment/kafka-init/Dockerfile
  deployment/kafka-state-detector/Dockerfile
  deployment/kafka-to-postgresql/Dockerfile
  deployment/mqtt-bridge/Dockerfile
  deployment/mqtt-kafka-bridge/Dockerfile
  deployment/sensorconnect/Dockerfile
Labels: status: ready for review

#1563 Removed duplicated DDL
  deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
Labels: status: ready for review
