Repository united-manufacturing-hub/united-manufacturing-hub, pull requests merged in 2023-01, with the labels that each got.

#1402 Chore: upgrade grafana chart to latest
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/grafana-6.21.1.tgz
  deployment/united-manufacturing-hub/charts/grafana-6.49.0.tgz
  deployment/united-manufacturing-hub/values.yaml
Labels: type: dependencies, lang: k8s

#1420 feat/12/Add processValueStrings
  golang/cmd/factoryinsight/v2/controllers/controller-tags.go
  golang/cmd/factoryinsight/v2/models/dto-tags.go
  golang/cmd/factoryinsight/v2/services/common.go
  golang/cmd/factoryinsight/v2/services/service-tags.go
  golang/cmd/factoryinsight/v2/services/service-tree.go
Labels: type: enhancement

#1419 fix/1410/Our_microservices_should_strictly_check_required_env_variables
  golang/cmd/barcodereader/main.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/sensorconnect/main.go
Labels: type: enhancement

#1415 feat: each microservice will now attempt to create the probeTopic
  golang/internal/kafka.go
Labels: type: enhancement

#1397 inconsistency #92 ReturnTimestampsInRFC3339InProductionSpeed
  golang/cmd/factoryinsight/v1/database.go
  golang/cmd/factoryinsight/v1/dataprocessing.go
  golang/cmd/factoryinsight/v1/http.go
Labels: flag: inconsistency

#1396 feat:updated kafka to 20.0.2
  deployment/united-manufacturing-hub/Chart.lock
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/kafka-20.0.2.tgz
Labels: type: enhancement

#1422 feat: added fgtrace
  deployment/mqtt-bridge/Dockerfile
  deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
  deployment/united-manufacturing-hub/templates/factoryinput/statefulset.yaml
  deployment/united-manufacturing-hub/templates/factoryinsight/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafka-state-detector/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafkabridge/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafkatoblob/deployment.yaml
  deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
  deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml
  deployment/united-manufacturing-hub/templates/mqttbridge/deployment.yaml
  deployment/united-manufacturing-hub/templates/sensorconnect/deployment.yaml
  deployment/united-manufacturing-hub/values.yaml
  golang/cmd/barcodereader/main.go
  golang/cmd/factoryinput/main.go
  golang/cmd/factoryinsight/main.go
  golang/cmd/grafana-proxy/main.go
  golang/cmd/kafka-bridge/main.go
  golang/cmd/kafka-debug/main.go
  golang/cmd/kafka-init/main.go
  golang/cmd/kafka-state-detector/main.go
  golang/cmd/kafka-to-blob/main.go
  golang/cmd/kafka-to-postgresql/main.go
  golang/cmd/mqtt-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/hash.go
  golang/cmd/mqtt-kafka-bridge/kafka.go
  golang/cmd/mqtt-kafka-bridge/main.go
  golang/cmd/mqtt-kafka-bridge/mqtt.go
  golang/cmd/mqtt-kafka-bridge/queue.go
  golang/cmd/sensorconnect/main.go
  golang/go.mod
  golang/go.sum
  golang/internal/exponential_backoff_test.go
  golang/internal/fgtrace.go
Labels: type: enhancement

#1380 Custom grafana image
  deployment/grafana-plugin-extractor/Dockerfile
  deployment/grafana-plugin-extractor/runner.sh
  deployment/grafana-umh/Dockerfile
  deployment/united-manufacturing-hub/Chart.yaml
  deployment/united-manufacturing-hub/charts/grafana-6.21.1.tgz
  deployment/united-manufacturing-hub/charts/grafana-6.49.0.tgz
  deployment/united-manufacturing-hub/values.yaml
Labels: type: enhancement, lang: docker, lang: k8s
